package(default_visibility = ["//visibility:public"])

cc_library(
    name = "rollout",
    srcs = ["rollout.cc"],
    hdrs = ["rollout.h"],
    deps = [
        "@arcade_learning_environment//:ale",
        "@libtorch//:torch",
    ],
)
